In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

Problem 1

In [2]:
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

In [3]:
x = tf.random_uniform([])
y = tf.random_uniform([])
obj1 = tf.cond(tf.greater(x,y), lambda:tf.add(x,y), lambda:tf.subtract(x,y))

In [4]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

In [12]:
x = tf.random_uniform([],-1, 1, dtype=tf.float32)
y = tf.random_uniform([],-1, 1, dtype=tf.float32)
obj2 = tf.case({tf.less(x,y): lambda : tf.add(x,y), tf.greater(x,y): lambda: tf.subtract(x,y)},default= lambda: tf.constant(0.0), exclusive=True)

print(x)
sess = tf.InteractiveSession()
print(sess.run(obj2))

Tensor("random_uniform_6:0", shape=(), dtype=float32)
1.40681


In [13]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

In [15]:
x = tf.constant([[0,-2,-1],[0,1,2]])
y = tf.zeros_like(x)
obj3 = tf.equal(x,y)
print(sess.run(obj3))

[[ True False False]
 [ True False False]]


In [16]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

In [19]:
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
30.97266006,  26.67541885,  38.08450317,  20.74983215,
34.94445419,  34.45999146,  29.06485367,  36.01657104,
27.88236427,  20.56035233,  30.20379066,  29.51215172,
33.71149445,  28.59134293,  36.05556488,  28.66994858])
indices = tf.where(x>30)
obj4 = tf.gather(x,indices)
print(sess.run(obj4))

[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


In [20]:
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().

In [23]:
x = tf.range(1,limit=7,delta=1)
y = tf.diag(x)
print(sess.run(y))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [24]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

In [26]:
x = tf.random_uniform([10,10])
y = tf.matrix_determinant(x)
print(sess.run(y))

-0.0339562


In [27]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

In [29]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
unique, indexes = tf.unique(x)
print(sess.run(unique))

[ 5  2  3 10  6  4  1  0  9]


In [30]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

In [35]:
x = tf.random_normal([300],mean=5,stddev=1)
y = tf.random_normal([300],mean=5,stddev=1)
average = tf.reduce_mean(x-y)
def f1(): return tf.reduce_mean(tf.square(x-y))
def f2(): return tf.reduce_mean(tf.abs(x-y))
obj4 = tf.cond(average<0,f1,f2)
print(sess.run(obj4))

1.94262


Problem 2

Improving accuracy of MNIST

In [37]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [38]:
type(mnist)

tensorflow.contrib.learn.python.learn.datasets.base.Datasets